# Generated by Django 5.1.6 on 2025-02-18 07:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="seed_phrase",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
