# Generated by Django 5.1.6 on 2025-02-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_wallet_seed_phrase"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="private_key",
            new_name="encrypted_private_key",
        ),
    ]
