# Generated by Django 5.1.6 on 2025-02-19 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_rename_private_key_wallet_encrypted_private_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="password",
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
